### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by PeterJohnson** [wpilibsuite/cameraserver#17]
- [x] Implement HttpCamera
- [ ] Implement HttpCamera properties
- [ ] Intermediate FPS support
- [x] Total ordering of UsbCamera streamon/streamoff (to avoid USB bandwidth limits when switching sources with SetSource) (#69)
- [x] Per-MJPEG server image scaling and FPS (when more than one sink connected) so dashboard settings don't change image processing
- [x] UsbCamera: Scaled 0-100 brightness, etc settings (not just raw)
- [x] UsbCamera: Exposure quirk for Microsoft LifeCam
- [x] WPILib: Finish NT bidirectional settings support
- [ ] MjpegServer: Write error message (e.g. "camera disconnected") as text on a black image for dashboard display (configurable setting)
- [ ] Add NiSource and NiSink to interface to nivision
- [ ] Add RawSource and RawSink to interface to nivision or other libraries
- [ ] Hoist Java OpenCV to Java layer (using RawSource/RawSink) to avoid static libs issues
- [ ] Performance improvement: don't copy UsbCamera image to memory but rather keep the kernel mmap buffer open?  Tradeoff on this due to user code delays (low priority)
- [x] Cache compressed / resized / color-converted images in Frame
- [x] MjpegServer: Improve HTML "root page" (e.g. allow settings changes)
- [x] Logger C/Java API (copy from ntcore)
- [x] Cross platform support (Windows)
- [ ] Cross platform support (Mac)
- [ ] MjpegServer: Support multiple streams multiplexed onto a single server port, selected by name GET parameter
- [x] Better error message for too much USB bandwidth usage (STREAMON failed due to no space left on device)
- [x] CameraServer: Fix NT settings
- [x] CameraServer: Provide access to MjpegServer object
- [x] CameraServer: Auto-increment camera number in startAutomaticCapture
